import Head from 'next/head'
import { useState } from 'react';
import Image from 'next/image';

export default function Home() {
  const [profileText, setProfileText] = useState('');

  const handleProfileTextChange = (event) => {
    setProfileText(event.target.value);
  }

  return (
    <div>
      <Head>
        <title>Ahmad Danindra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='bg-black h-screen'>
          <nav className='p-10'>
            <h1 className="text-center my-20 text-3xl hover:scale-150 transition text-white font-bold font-mono">Hometown</h1>
            <div className="my-2 flex gap-10 items-center justify-center">
                <div className='text-right font-mono text-xl w-96 text-white overflow-clip'>
                    <h1>Bekasi is a growing city in West Java, Indonesia with over 2.5 million residents. It's located near Jakarta and is known for its cultural landmarks, diverse cuisine, and thriving economy. Despite its development, Bekasi has maintained its green spaces and natural beauty. Overall, it's a lively city that offers modern amenities and cultural attractions.</h1>
                </div>
                <Image
                className='rounded-xl'
                src='/bekasi.jpg'
                alt=''
                width={463.2}
                height={529.9}
                />
            </div>
            <div className=''>
                <h1 className=' hover:text-xl mt-52 text-white'>
                    <a href="/">Back</a>
                </h1>
            </div>
            
</nav>
</section>
</main>
</div>
)
}