import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ahmad Danindra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='bg-black h-screen'>
          <nav className='p-10'>
            <h1 className="text-center my-20 text-5xl hover:scale-150 transition text-white font-boldul font-mono">Ahmad Danindra</h1>
            <div className="text-center mb-10">
            </div>
            <ul className='text-center mt-28 text-xl text-white'>
              <li className="shadow-xl rounded-xl mx-5 my-5 min-h-min cursor-pointer">
                <button className="border-2 border-white text-white hover:bg-white hover:text-black py-2 px-4 rounded-full hover:animate-pulse w-56">
                  <Link href="/profile">Profile</Link>
                </button>
              </li>
              <li className="shadow-xl rounded-xl mx-5 my-5 min-h-min cursor-pointer">
                <button className="border-2 border-white text-white hover:bg-white hover:text-black py-2 px-4 rounded-full hover:animate-pulse w-56">
                  <Link ahref="/hometown">Hometown</Link>
                </button>
              </li>
              <li className="shadow-xl rounded-xl mx-5 my-5 min-h-min cursor-pointer">
                <button className="border-2 border-white text-white hover:bg-white hover:text-black py-2 px-4 rounded-full hover:animate-pulse w-56">
                  <Link href="/food">Food</Link>
                </button>
              </li>
              <li className="shadow-xl rounded-xl mx-5 my-5 min-h-min cursor-pointer">
                <button className="border-2 border-white text-white hover:bg-white hover:text-black py-2 px-4 rounded-full hover:animate-pulse w-56">
                  <Link href="/tourist">Tourist</Link>
                </button>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  )
}
